# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rb6oNJVkQDu9L2jhfKedIwcAjpuTnGVA
"""

#Câu 1:
n=input("Nhap n:")
print("So dao nguoc la:",n[::-1])

#Câu 3:
def kiem_tra_luy_thua_cua_2(n):
    if n>0 and (n&(n-1)==0):
      return True
    else:
      return False
n=int(input("Nhap n:"))
print(f"Ket qua kiem tra luy thua cua 2 cho {n}:{kiem_tra_luy_thua_cua_2(n)}")

#Câu 5
m=int(input("Nhap m:"))
n=int(input("Nhap n:"))
if n==0:
  print("Khong the chia cho 0")
else:
 ket_qua=(m+n-1)//n
print(ket_qua)

#Câu 4
m=int(input("Nhap m:"))
n=int(input("Nhap n:"))
if n==0:
  print("Khong the chia cho 0")
else:
 ket_qua=(m-n+1)//n
print(ket_qua)

#Câu 6
x=int(input("Nhap x:"))
ket_qua=x%2
if ket_qua==0:
  print("Even")
else:
  print("Odd")